Cloud:
  provider: nutanix
  cvm_ip: 192.168.122.3
Credential:
  username: admin
  password: 
VM:
  rhel_ver: '8.5'
  username: root
  password: redhat
  vm_name: avocado_cloud
  image_name: rhel-guest-image-8.5-1248
  storage_container_uuid: 4769f83c-73ac-44e5-9750-986f45438672
  network_uuid: 5ccd2f0e-afc9-4695-8cf1-4956ec67a308
