cases:
  test_functional_lifecycle.py:LifeCycleTest.test_create_vm_password
  test_functional_lifecycle.py:LifeCycleTest.test_stop_vm
  test_functional_lifecycle.py:LifeCycleTest.test_start_vm
  test_functional_lifecycle.py:LifeCycleTest.test_reboot_vm
  test_functional_lifecycle.py:LifeCycleTest.test_reboot_inside_vm
  test_functional_lifecycle.py:LifeCycleTest.test_delete_vm