Cloud:
  provider: nutanix
  cvm_ip: 192.168.122.3
Credential:
  username: admin
  password: 
Subscription:
  username: 
  password: 
VM:
  rhel_ver: '8.5'
  username: cloud-user
  password: redhat
  keypair: xen-jenkins
  vm_name: avocado_cloud
  image_name: 
  storage_container_uuid: 
  network_uuid: 
  custom_data:
Other:
  packages: 
